#  Copyright © Microsoft Corporation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

LOG_PREFIX=legal
server.servlet.contextPath=/api/legal/v1/

REGION=${legal_service_region}
AUTHORIZE_API=${entitlements_service_endpoint}
AUTHORIZE_API_KEY=${entitlements_service_api_key}

# Partition Service configuration
PARTITION_API=${partition_service_endpoint}
azure.activedirectory.app-resource-id=${aad_client_id}

LEGAL_HOSTNAME=notused
CRON_JOB_IP=10.0.0.1

# Azure AD configuration for OpenIDConnect, commented below settings to disable AAD AuthN ,
# Uncomment it In the Istio AUTHN disabled Scenario
#azure.activedirectory.client-id=${aad_client_id}
#azure.activedirectory.AppIdUri=api://${azure.activedirectory.client-id}
#azure.activedirectory.session-stateless=true

# Istio Auth Enabled
azure.istio.auth.enabled=${azure_istioauth_enabled}

# Azure CosmosDB configuration
azure.cosmosdb.database=${cosmosdb_database}
azure.cosmosdb.legal.collection=LegalTag

# Azure Blob Storage configuration
azure.storage.container-name=legal-service-azure-configuration
azure.storage.enable-https=true
azure.blobStore.required=true

# Azure Service Bus configuration
azure.servicebus.topic-name=${servicebus_topic_name}

# Azure Event Grid Configuration
azure.publishToEventGrid=false
azure.eventGridBatchSize=10
azure.eventGrid.topicName=legaltagschangedtopic

# Azure KeyVault configuration
azure.keyvault.url=${KEYVAULT_URI}

#Azure App Insights configuration
azure.application-insights.instrumentation-key=${appinsights_key}
spring.application.name=legal-azure

#logging configuration
logging.transaction.enabled=true
logging.slf4jlogger.enabled=true
log.sampling.enabled=${log_sampling_enabled:false}
log.sampling.info=${log_sampling_info:100}
log.sampling.dependency=${log_sampling_dependency:100}
logging.mdccontext.enabled=true
logging.ignore.servlet.paths=/swagger-ui.html

#TenantFactory Configuration
tenantFactoryImpl.required=true
tenantInfo.container.name=TenantInfo

# Disable keyVault for actuator health check
management.health.azure-key-vault.enabled=false
management.server.port=8081

#Swagger config
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.doc-expansion=none
# To enable the full server path url in OpenAPI Swagger
api.server.fullUrl.enabled=${swaggerFullUrlEnabled:true}

# Feature flag settings
featureFlag.strategy=appProperty
featureFlag.aboutToExpireLegalTag.enabled=true
featureFlag.legalTagQueryApi.enabled=true
featureFlag.legalTagQueryApiFreeTextAllFields.enabled=false

# Cache configuration, provider [vm, redis]
cache.provider=redis

# Redis
redis.port=${REDIS_SSL_PORT:6380}
redis.ssl.enabled=true
redis.database=${REDIS_DATABASE}
redis.principal.id=${REDIS_PRINCIPAL_ID:}
redis.hostname=${REDIS_HOSTNAME:}

# MSI (Managed Service Identity) configuration
azure.msi.isEnabled=${AZURE_MSI_ISENABLED:true}