# Default values for legal-deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  domain: ""
  limitsEnabled: true
  dataPartitionId: ""

data:
  # configmaps
  logLevel: "ERROR"
  acceptHttp: "true"
  entitlementsHost: "http://entitlements"
  defaultLegalTag: "default-data-tag"
  legalHost: "http://legal"
  partitionHost: "http://partition"
  # deployments
  requestsCpu: "5m"
  requestsMemory: "325Mi"
  limitsCpu: "1"
  limitsMemory: "1G"
  legalStatusUpdateImage: ""
  cronJobServiceAccountName: ""
  serviceAccountName: "legal"
  imagePullPolicy: "IfNotPresent"
  image: ""

conf:
  configmap: "legal-config"
  appName: "legal"
  s3SecretName: "legal-seaweedfs-secret"
  postgresSecretName: "legal-postgres-secret"
  rabbitmqSecretName: "rabbitmq-secret"
  bootstrapSecretName: "datafier-secret"
  replicas: 1

istio:
  proxyCPU: "5m"
  proxyCPULimit: "500m"
  proxyMemory: "50Mi"
  proxyMemoryLimit: "512Mi"
